# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the csi2115-f21 branch
  push:
    branches: [ csi2115-f21 ]
  pull_request:
    branches: [ csi2115-f21 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Download
        run: wget https://github.com/OSS-SSH/linux/archive/${GITHUB_SHA}.zip
            
      - name: Unzip
        run: unzip -qq ${GITHUB_SHA}.zip
        
      - name: Build
        run: ./install-deps.sh
             ./build-linux.sh ${GITHUB_SHA}
